import Link from "next/link";
import type { buildBusinessIntelligence } from "@/backend/shared/business-intelligence";

type IntelligenceModel = ReturnType<typeof buildBusinessIntelligence>;
type View = "overview" | "performance" | "flow" | "services" | "vehicles" | "customers" | "employees" | "finance" | "payments" | "forecast" | "copilot";

const views: Array<[View, string]> = [["overview", "Visão geral"], ["performance", "Desempenho"], ["flow", "Fluxo"], ["services", "Serviços"], ["vehicles", "Veículos e ativos"], ["customers", "Clientes"], ["employees", "Colaboradores"], ["finance", "Financeiro"], ["payments", "Pagamentos"], ["forecast", "Previsões"], ["copilot", "Copiloto IA"]];
const currency = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);

export function BusinessIntelligenceSection({ model, view }: { model: IntelligenceModel; view: View }) {
  const unavailable = ["Ainda não há dados suficientes para gerar esta análise."];
  const hasOperationalData = model.serviceGroups.length > 0;
  return <section className="space-y-5"><div className="flex flex-wrap gap-2">{views.map(([id, label]) => <Link key={id} href={`/app/dashboard?section=inteligencia&intelligenceView=${id}`} className={`rounded-xl border px-3 py-2 text-xs font-medium ${view === id ? "border-[var(--accent)] bg-[var(--accent)] text-slate-950" : "border-white/10 bg-white/5 text-white/70"}`}>{label}</Link>)}</div><div className="flex items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.2em] text-white/45">Período real</p><p className="mt-1 text-sm text-white/70">{model.periodLabel}</p></div></div>{view === "overview" ? <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Receita" value={currency(model.metrics.income)} /><Metric label="Saídas" value={currency(model.metrics.expenses)} /><Metric label="Resultado" value={currency(model.metrics.result)} /><Metric label="Atendimentos" value={String(model.metrics.attendanceCount)} /><Metric label="Ticket médio" value={model.metrics.attendanceCount ? currency(model.metrics.ticket) : "Sem dados"} /></div><InsightPanel insights={model.insights} /></> : view === "finance" ? <div className="grid gap-4 lg:grid-cols-2"><GroupPanel title="De onde vem a receita" groups={model.incomeGroups} /><GroupPanel title="Para onde vão as saídas" groups={model.expenseGroups} /></div> : view === "services" ? <GroupPanel title="Serviços registrados" groups={model.serviceGroups.map((item) => ({ label: `${item.label} · ${item.count} atendimentos`, amount: item.revenue }))} empty={!hasOperationalData} /> : view === "vehicles" ? <CountPanel title="Distribuição por categoria de ativo" groups={model.vehicleGroups} /> : <EmptyIntelligence text={unavailable[0]} />}</section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs uppercase tracking-[0.16em] text-white/45">{label}</p><p className="mt-2 text-xl font-semibold text-white">{value}</p></div>; }
function InsightPanel({ insights }: { insights: string[] }) { return <div className="rounded-3xl border border-cyan-300/20 bg-[linear-gradient(135deg,rgba(34,211,238,.12),rgba(15,23,42,.5))] p-5"><p className="text-lg font-semibold text-white">O que está acontecendo?</p>{insights.length ? <ul className="mt-3 space-y-2 text-sm text-white/75">{insights.map((item) => <li key={item}>• {item}</li>)}</ul> : <EmptyIntelligence text="Ainda não há dados suficientes para gerar esta análise." />}</div>; }
function GroupPanel({ title, groups, empty = false }: { title: string; groups: Array<{ label: string; amount: number }>; empty?: boolean }) { return <div className="rounded-3xl border border-white/10 bg-black/15 p-5"><p className="text-lg font-semibold text-white">{title}</p>{empty || !groups.length ? <EmptyIntelligence text="Ainda não há dados suficientes para gerar esta análise." /> : <div className="mt-4 space-y-3">{groups.map((item) => <div key={item.label}><div className="flex justify-between gap-3 text-sm text-white/75"><span>{item.label}</span><strong className="text-white">{currency(item.amount)}</strong></div><div className="mt-1 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-300" style={{ width: `${Math.max(6, Math.min(100, item.amount / Math.max(...groups.map((group) => group.amount), 1) * 100))}%` }} /></div></div>)}</div>}</div>; }
function CountPanel({ title, groups }: { title: string; groups: Array<{ label: string; count: number }> }) { return <div className="rounded-3xl border border-white/10 bg-black/15 p-5"><p className="text-lg font-semibold text-white">{title}</p>{groups.length ? <div className="mt-4 space-y-3">{groups.map((item) => <div key={item.label} className="flex justify-between text-sm text-white/75"><span>{item.label}</span><strong className="text-white">{item.count}</strong></div>)}</div> : <EmptyIntelligence text="Ainda não há dados suficientes para gerar esta análise." />}</div>; }
function EmptyIntelligence({ text }: { text: string }) { return <p className="mt-4 rounded-2xl border border-dashed border-white/10 p-4 text-sm text-white/50">{text}</p>; }
