import Link from "next/link";
import type { ReactNode } from "react";
import type { getBusinessIntelligenceUseCase } from "@/backend/use-cases/tenant/get-business-intelligence";
import { IntelligenceChart } from "@/components/intelligence-chart";

type Model = Awaited<ReturnType<typeof getBusinessIntelligenceUseCase>>;
type View = "overview" | "performance" | "flow" | "services" | "vehicles" | "customers" | "employees" | "finance" | "payments" | "forecast" | "copilot";
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
const tabs: Array<[View, string]> = [["overview", "Visão geral"], ["performance", "Desempenho"], ["flow", "Operação"], ["customers", "Clientes"], ["employees", "Colaboradores"], ["payments", "Pagamentos"], ["forecast", "Previsões"], ["copilot", "Copiloto IA"]];
const periods = [["today", "Hoje"], ["7d", "7 dias"], ["14d", "14 dias"], ["30d", "30 dias"], ["month", "Este mês"], ["previous_month", "Mês anterior"], ["3m", "3 meses"]];

export function BusinessIntelligenceSection({ model, view, period }: { model: Model; view: View; period: string }) {
  const activeView = view === "finance" || view === "services" || view === "vehicles" || view === "payments" ? "overview" : view;
  const link = (nextView: View, nextPeriod = period) => `/app/dashboard?section=inteligencia&intelligenceView=${nextView}&intelligencePeriod=${nextPeriod}`;
  return <div className="space-y-5">
    <nav className="flex flex-wrap gap-2">{tabs.map(([id, label]) => <Link key={id} href={link(id)} className={`rounded-xl border px-3 py-2 text-xs font-medium transition ${activeView === id ? "border-[var(--accent)] bg-[var(--accent)] text-slate-950" : "border-white/10 bg-white/5 text-white/70 hover:border-cyan-300/40 hover:text-white"}`}>{label}</Link>)}</nav>
    <div className="flex flex-wrap gap-2">{periods.map(([id, label]) => <Link key={id} href={link(activeView as View, id)} className={`rounded-xl border px-3 py-2 text-xs transition ${period === id ? "border-cyan-300/60 bg-cyan-300/15 text-cyan-100" : "border-white/10 text-white/55 hover:border-white/25"}`}>{label}</Link>)}</div>
    {activeView === "overview" ? <Overview model={model} /> : activeView === "performance" ? <Performance model={model} /> : activeView === "flow" ? <Flow model={model} /> : activeView === "customers" ? <Customers model={model} /> : activeView === "employees" ? <Counts title="Colaboradores" rows={model.current.employees.map((item) => ({ label: item.label, count: item.count, detail: item.averageMinutes ? `${item.averageMinutes} min médios` : "tempo não disponível" }))} /> : activeView === "forecast" ? <Forecast model={model} /> : activeView === "copilot" ? <Copilot model={model} /> : <Overview model={model} />}
  </div>;
}

function Panel({ title, subtitle, children, className = "" }: { title: string; subtitle?: string; children: ReactNode; className?: string }) { return <section className={`rounded-[26px] border border-white/10 bg-[#151a21] p-5 shadow-[0_18px_50px_rgba(0,0,0,.16)] ${className}`}><div><h3 className="text-lg font-semibold text-white">{title}</h3>{subtitle ? <p className="mt-1 text-xs text-white/45">{subtitle}</p> : null}</div>{children}</section>; }

function Overview({ model }: { model: Model }) { return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Receita" value={money(model.current.metrics.income)} change={model.comparisons.income} tone="cyan" /><Metric label="Saídas" value={money(model.current.metrics.expenses)} change={model.comparisons.expenses} tone="rose" /><Metric label="Resultado" value={money(model.current.metrics.result)} tone="emerald" /><Metric label="Atendimentos" value={String(model.current.metrics.attendances)} change={model.comparisons.attendances} tone="violet" /><Metric label="Ticket médio" value={model.current.metrics.ticket ? money(model.current.metrics.ticket) : "Sem dados"} change={model.comparisons.ticket} tone="amber" /></div><Panel title="Receita e custos no período" subtitle="Leitura financeira consolidada para decisão rápida"><div className="mt-4 grid gap-4 lg:grid-cols-2"><IntelligenceChart type="mix" data={model.current.services.slice(0, 8)} /><IntelligenceChart type="finance" data={[{ label: "Receita", amount: model.current.metrics.income }, { label: "Saídas", amount: model.current.metrics.expenses }, { label: "Resultado", amount: Math.max(0, model.current.metrics.result) }]} /></div></Panel><Panel title="Demonstrativo financeiro" subtitle="De onde veio o dinheiro e para onde ele foi"><div className="mt-4 grid gap-4 lg:grid-cols-2"><Amounts title="Receitas por origem" rows={model.current.income} tone="income" /><Amounts title="Saídas por categoria" rows={model.current.expense} tone="expense" /></div></Panel><Panel title="Pagamentos" subtitle="Como os recebimentos foram realizados"><div className="mt-4"><IntelligenceChart type="payments" data={model.current.payments} /></div></Panel><InsightStrip model={model} /></div>; }

function Performance({ model }: { model: Model }) { const incomeDelta = model.current.metrics.income - model.previous.metrics.income; const ticketDelta = model.current.metrics.ticket - model.previous.metrics.ticket; return <div className="space-y-4"><Panel title="Desempenho do negócio" subtitle={`Comparação entre ${model.period.label} e o período equivalente anterior`}><div className="mt-4 grid gap-3 md:grid-cols-2"><Comparison label="Receita" current={model.current.metrics.income} previous={model.previous.metrics.income} change={model.comparisons.income} color="cyan" /><Comparison label="Atendimentos" current={model.current.metrics.attendances} previous={model.previous.metrics.attendances} change={model.comparisons.attendances} color="violet" /><Comparison label="Ticket médio" current={model.current.metrics.ticket} previous={model.previous.metrics.ticket} change={model.comparisons.ticket} color="amber" /><Comparison label="Resultado operacional" current={model.current.metrics.result} previous={model.previous.metrics.result} change={null} color="emerald" /></div></Panel><Panel title="O que mudou?" subtitle="Interpretação automática dos números"><div className="mt-4 grid gap-3 md:grid-cols-3"><Narrative icon="↑" title={incomeDelta >= 0 ? "Receita em alta" : "Receita em queda"} text={`${money(Math.abs(incomeDelta))} ${incomeDelta >= 0 ? "a mais" : "a menos"} que no período anterior.`} tone={incomeDelta >= 0 ? "good" : "bad"} /><Narrative icon="◆" title="Ritmo operacional" text={`${model.current.metrics.attendances} atendimentos, com ticket médio de ${money(model.current.metrics.ticket)}.`} tone="info" /><Narrative icon="↗" title={ticketDelta >= 0 ? "Ticket evoluiu" : "Ticket recuou"} text={`${money(Math.abs(ticketDelta))} ${ticketDelta >= 0 ? "acima" : "abaixo"} da média anterior.`} tone={ticketDelta >= 0 ? "good" : "bad"} /></div></Panel><Panel title="Serviços que puxam o resultado" subtitle="Receita, volume e participação"><IntelligenceChart type="services" data={model.current.services.slice(0, 8)} /></Panel></div>; }

function Flow({ model }: { model: Model }) { return <div className="space-y-4"><Panel title="Fluxo operacional" subtitle="Quando a operação concentra demanda"><IntelligenceChart type="flow" data={{ weekday: model.current.weekday, hour: model.current.hour }} /></Panel><Panel title="Serviços" subtitle="Volume e receita por serviço"><IntelligenceChart type="services" data={model.current.services.slice(0, 8)} /></Panel><Panel title="Ativos por categoria" subtitle="Distribuição de atendimentos e receita"><IntelligenceChart type="vehicles" data={model.current.vehicles} /></Panel><Panel title="Mapa de ocupação" subtitle="Intensidade por dia da semana e horário"><IntelligenceChart type="heatmap" data={model.current.heatmap.flat()} /></Panel></div>; }
function InsightStrip({ model }: { model: Model }) { return <Panel title="Leitura executiva" subtitle="O que merece atenção neste período"><div className="mt-4 grid gap-3 md:grid-cols-3">{model.recommendations.slice(0, 3).map((item, index) => <Narrative key={item} icon={index === 0 ? "✦" : index === 1 ? "↗" : "!"} title={index === 0 ? "Prioridade" : index === 1 ? "Oportunidade" : "Atenção"} text={item} tone={index === 2 ? "warn" : "info"} />)}</div></Panel>; }
function Customers({ model }: { model: Model }) { const c = model.current.customers; return <div className="space-y-4"><Panel title="Clientes" subtitle="Relacionamento e recorrência no período"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 mt-4"><Metric label="Clientes cadastrados" value={String(c.total)} tone="cyan" /><Metric label="Com atendimento" value={String(c.active)} tone="violet" /><Metric label="Recorrentes" value={String(c.recurrent)} tone="emerald" /><Metric label="Novos no período" value={String(c.newInPeriod)} tone="amber" /></div></Panel><Panel title="Sinal de relacionamento" subtitle="Leitura dos clientes que movimentaram a operação"><div className="mt-4 grid gap-3 md:grid-cols-2"><Narrative icon="◎" title="Base ativa" text={`${c.active} clientes tiveram atendimento em ${model.period.label.toLowerCase()}.`} tone="info" /><Narrative icon="↻" title="Retenção" text={`${c.recurrent} clientes retornaram mais de uma vez no período.`} tone="good" /></div></Panel></div>; }
function Forecast({ model }: { model: Model }) { return <div className="space-y-4"><Panel title="Previsões" subtitle="Estimativa baseada no comportamento observado"><div className="mt-4 rounded-[22px] border border-cyan-300/20 bg-[linear-gradient(135deg,rgba(34,211,238,.16),rgba(15,23,42,.72))] p-5"><p className="text-sm font-semibold uppercase tracking-[.16em] text-cyan-200">Próximo período</p>{model.forecast.available ? <><div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Receita projetada" value={money(model.forecast.projectedIncome ?? 0)} tone="cyan" /><Metric label="Atendimentos projetados" value={String(model.forecast.projectedAttendances)} tone="violet" /></div><p className="mt-4 text-sm leading-6 text-white/75">A projeção repete o ritmo de receita e volume observado no período selecionado. Use-a como referência para capacidade, compras e escala.</p></> : <p className="mt-4 text-sm leading-6 text-white/70">Ainda não há histórico comparável suficiente. A previsão será liberada após cinco atendimentos em cada período.</p>}</div><p className="mt-4 text-xs text-white/40">Base do cálculo: {model.forecast.basis}. Estimativa, não promessa de resultado.</p></Panel><Panel title="Sinais que sustentam a previsão" subtitle="Indicadores usados no cálculo"><div className="mt-4 grid gap-3 md:grid-cols-3"><Narrative icon="▣" title="Histórico" text={`${model.current.metrics.attendances} atendimentos analisados.`} tone="info" /><Narrative icon="R$" title="Receita observada" text={money(model.current.metrics.income)} tone="good" /><Narrative icon="◷" title="Período" text={model.period.label} tone="warn" /></div></Panel></div>; }
function Copilot({ model }: { model: Model }) { return <Panel title="Copiloto IA" subtitle="Resumo acionável dos dados reais do período"><div className="mt-4 space-y-3">{model.insights.length ? model.insights.map((item, index) => <div key={item} className="flex gap-3 rounded-2xl border border-cyan-300/15 bg-cyan-300/[.06] p-4 text-sm leading-6 text-white/80"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-cyan-300/15 text-cyan-200">{index + 1}</span>{item}</div>) : <Empty text="Ainda não há dados suficientes para gerar uma análise." />}</div></Panel>; }
function Metric({ label, value, change, tone = "cyan" }: { label: string; value: string; change?: number | null; tone?: "cyan" | "rose" | "emerald" | "violet" | "amber" }) { const colors = { cyan: "border-cyan-300/35", rose: "border-rose-300/30", emerald: "border-emerald-300/30", violet: "border-violet-300/30", amber: "border-amber-300/30" }; return <div className={`rounded-2xl border bg-white/[.045] p-4 ${colors[tone]}`}><p className="text-[10px] uppercase tracking-[.16em] text-white/45">{label}</p><p className="mt-2 text-xl font-semibold text-white">{value}</p>{change !== undefined ? <p className={`mt-1 text-xs ${change === null ? "text-white/45" : change >= 0 ? "text-emerald-300" : "text-rose-300"}`}>{change === null ? "Sem comparação" : `${change >= 0 ? "+" : ""}${change}% vs. anterior`}</p> : null}</div>; }
function Comparison({ label, current, previous, change, color }: { label: string; current: number; previous: number; change: number | null; color: "cyan" | "violet" | "amber" | "emerald" }) { const max = Math.max(current, previous, 1); return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="flex justify-between gap-3"><span className="text-sm font-medium text-white/75">{label}</span><span className="text-xs text-white/40">{change === null ? "" : `${change >= 0 ? "+" : ""}${change}%`}</span></div><div className="mt-4 space-y-3"><BarLine label="Atual" value={current} max={max} color={color} /><BarLine label="Anterior" value={previous} max={max} color="slate" /></div></div>; }
function BarLine({ label, value, max, color }: { label: string; value: number; max: number; color: string }) { const colors: Record<string, string> = { cyan: "bg-cyan-300", violet: "bg-violet-300", amber: "bg-amber-300", emerald: "bg-emerald-300", slate: "bg-white/20" }; return <div><div className="flex justify-between text-xs text-white/55"><span>{label}</span><strong className="text-white/80">{typeof value === "number" && value > 999 ? money(value) : value}</strong></div><div className="mt-1 h-2 rounded-full bg-white/8"><div className={`h-full rounded-full ${colors[color] ?? colors.slate}`} style={{ width: `${Math.max(value ? 7 : 0, value / max * 100)}%` }} /></div></div>; }
function Narrative({ icon, title, text, tone }: { icon: string; title: string; text: string; tone: "good" | "bad" | "info" | "warn" }) { const styles = { good: "border-emerald-300/20 bg-emerald-300/[.07] text-emerald-200", bad: "border-rose-300/20 bg-rose-300/[.07] text-rose-200", info: "border-cyan-300/20 bg-cyan-300/[.07] text-cyan-200", warn: "border-amber-300/20 bg-amber-300/[.07] text-amber-200" }; return <div className={`rounded-2xl border p-4 ${styles[tone]}`}><div className="flex items-center gap-2 text-sm font-semibold"><span>{icon}</span>{title}</div><p className="mt-2 text-sm leading-6 text-white/70">{text}</p></div>; }
function Amounts({ title, rows, tone }: { title: string; rows: Array<{ label: string; amount: number }>; tone: "income" | "expense" }) { const max = Math.max(...rows.map((row) => row.amount), 1); return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="text-sm font-semibold text-white">{title}</p>{rows.length ? <div className="mt-4 space-y-3">{rows.slice(0, 8).map((row, index) => <div key={row.label}><div className="flex justify-between gap-3 text-sm"><span className="truncate text-white/70">{row.label}</span><strong className="text-white">{money(row.amount)}</strong></div><div className="mt-1 h-2 rounded-full bg-white/10"><div className={`h-full rounded-full ${tone === "income" ? ["bg-cyan-300", "bg-emerald-300", "bg-sky-300", "bg-violet-300"][index % 4] : ["bg-rose-300", "bg-amber-300", "bg-orange-300", "bg-pink-300"][index % 4]}`} style={{ width: `${Math.max(5, row.amount / max * 100)}%` }} /></div></div>)}</div> : <Empty text="Sem lançamentos no período." />}</div>; }
function Counts({ title, rows }: { title: string; rows: Array<{ label: string; count: number; detail: string }> }) { return <Panel title={title} subtitle="Volume registrado no período">{rows.some((row) => row.count) ? <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map((row) => <div key={row.label} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-sm text-white/70">{row.label}</p><p className="mt-2 text-2xl font-semibold text-white">{row.count}</p><p className="mt-1 text-xs text-white/40">{row.detail}</p></div>)}</div> : <Empty text="Ainda não há dados suficientes para gerar esta análise." />}</Panel>; }
function Empty({ text }: { text: string }) { return <p className="rounded-2xl border border-dashed border-white/10 p-4 text-sm text-white/50">{text}</p>; }
