import Link from "next/link";
import type { getBusinessIntelligenceUseCase } from "@/backend/use-cases/tenant/get-business-intelligence";
import { IntelligenceChart } from "@/components/intelligence-chart";

type Model = Awaited<ReturnType<typeof getBusinessIntelligenceUseCase>>;
type View = "overview" | "performance" | "flow" | "services" | "vehicles" | "customers" | "employees" | "finance" | "payments" | "forecast" | "copilot";
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
const tabs: Array<[View, string]> = [["overview", "Visão geral"], ["performance", "Desempenho"], ["flow", "Fluxo"], ["services", "Serviços"], ["vehicles", "Ativos"], ["customers", "Clientes"], ["employees", "Colaboradores"], ["finance", "Financeiro"], ["payments", "Pagamentos"], ["forecast", "Previsões"], ["copilot", "Copiloto IA"]];
const periods = [["today", "Hoje"], ["7d", "7 dias"], ["14d", "14 dias"], ["30d", "30 dias"], ["month", "Este mês"], ["previous_month", "Mês anterior"], ["3m", "3 meses"]];

export function BusinessIntelligenceSection({ model, view, period }: { model: Model; view: View; period: string }) {
  const link = (nextView: View, nextPeriod = period) => `/app/dashboard?section=inteligencia&intelligenceView=${nextView}&intelligencePeriod=${nextPeriod}`;
  return <div className="space-y-5"><nav className="flex flex-wrap gap-2">{tabs.map(([id, label]) => <Link key={id} href={link(id)} className={`rounded-xl border px-3 py-2 text-xs font-medium ${view === id ? "border-[var(--accent)] bg-[var(--accent)] text-slate-950" : "border-white/10 bg-white/5 text-white/70"}`}>{label}</Link>)}</nav><div className="flex flex-wrap gap-2">{periods.map(([id, label]) => <Link key={id} href={link(view, id)} className={`rounded-xl border px-3 py-2 text-xs ${period === id ? "border-cyan-300/60 bg-cyan-300/15 text-cyan-100" : "border-white/10 text-white/55"}`}>{label}</Link>)}</div>{view === "overview" ? <Overview model={model} /> : view === "performance" ? <Performance model={model} /> : view === "flow" ? <Flow model={model} /> : view === "services" ? <Amounts title="Serviços" rows={model.current.services.map((item) => ({ label: `${item.label} · ${item.count} atendimentos`, amount: item.revenue }))} /> : view === "vehicles" ? <Amounts title="Ativos por categoria" rows={model.current.vehicles.map((item) => ({ label: `${item.label} · ${item.count} atendimentos`, amount: item.revenue }))} /> : view === "customers" ? <Customers model={model} /> : view === "employees" ? <Counts title="Colaboradores" rows={model.current.employees.map((item) => ({ label: item.label, count: item.count, detail: item.averageMinutes ? `${item.averageMinutes} min médios` : "tempo não disponível" }))} /> : view === "finance" ? <div className="grid gap-4 lg:grid-cols-2"><Amounts title="Fontes de receita" rows={model.current.income} /><Amounts title="Categorias de saída" rows={model.current.expense} /></div> : view === "payments" ? <Counts title="Meios de pagamento" rows={model.current.payments.map((item) => ({ label: item.label, count: item.count, detail: money(item.amount) }))} /> : view === "forecast" ? <Forecast model={model} /> : <Copilot model={model} />}</div>;
}
function Overview({ model }: { model: Model }) { return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Receita" value={money(model.current.metrics.income)} change={model.comparisons.income} /><Metric label="Saídas" value={money(model.current.metrics.expenses)} change={model.comparisons.expenses} /><Metric label="Resultado" value={money(model.current.metrics.result)} /><Metric label="Atendimentos" value={String(model.current.metrics.attendances)} change={model.comparisons.attendances} /><Metric label="Ticket médio" value={model.current.metrics.ticket ? money(model.current.metrics.ticket) : "Sem dados"} change={model.comparisons.ticket} /></div><div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-3xl border border-white/10 bg-black/15 p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-lg font-semibold text-white">Onde a receita está concentrada?</p><p className="mt-1 text-xs text-white/45">Distribuição por serviço no período</p></div><span className="rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-[10px] uppercase tracking-[.16em] text-cyan-200">Ao vivo</span></div><IntelligenceChart type="mix" data={model.current.services.slice(0, 8)} /></div><div className="rounded-3xl border border-white/10 bg-black/15 p-5"><p className="text-lg font-semibold text-white">Fontes de receita</p><IntelligenceChart type="services" data={model.current.services.slice(0, 6)} /></div></div><div className="rounded-3xl border border-cyan-300/20 bg-[linear-gradient(135deg,rgba(34,211,238,.12),rgba(15,23,42,.5))] p-5"><p className="text-lg font-semibold text-white">Recomendações</p><ul className="mt-3 space-y-2 text-sm text-white/75">{model.recommendations.map((item) => <li key={item}>• {item}</li>)}</ul></div></>; }
function Performance({ model }: { model: Model }) { return <div className="grid gap-4 md:grid-cols-2"><Metric label="Receita atual x anterior" value={`${money(model.current.metrics.income)} x ${money(model.previous.metrics.income)}`} change={model.comparisons.income} /><Metric label="Atendimentos atual x anterior" value={`${model.current.metrics.attendances} x ${model.previous.metrics.attendances}`} change={model.comparisons.attendances} /><Metric label="Clientes recorrentes" value={String(model.current.customers.recurrent)} /><Metric label="Resultado operacional" value={money(model.current.metrics.result)} /></div>; }
function Flow({ model }: { model: Model }) { return <div className="space-y-4"><div className="grid gap-4 lg:grid-cols-2"><Counts title="Fluxo por dia da semana" rows={model.current.weekday.map((item) => ({ label: item.label, count: item.count, detail: "atendimentos" }))} /><Counts title="Fluxo por horário" rows={model.current.hour.filter((item) => item.count > 0).map((item) => ({ label: item.label, count: item.count, detail: "atendimentos" }))} /></div><div className="rounded-3xl border border-white/10 bg-black/15 p-5"><p className="text-lg font-semibold text-white">Mapa de ocupação por dia e horário</p><IntelligenceChart type="heatmap" data={model.current.heatmap.flat()} /></div></div>; }
function Customers({ model }: { model: Model }) { const c = model.current.customers; return <div className="grid gap-4 sm:grid-cols-3"><Metric label="Clientes cadastrados" value={String(c.total)} /><Metric label="Com atendimento no período" value={String(c.active)} /><Metric label="Recorrentes" value={String(c.recurrent)} /><Metric label="Novos no período" value={String(c.newInPeriod)} /></div>; }
function Forecast({ model }: { model: Model }) { return <div className="rounded-3xl border border-white/10 bg-black/15 p-5"><p className="text-lg font-semibold text-white">Previsão do próximo período</p>{model.forecast.available ? <div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Receita projetada" value={money(model.forecast.projectedIncome ?? 0)} /><Metric label="Atendimentos projetados" value={String(model.forecast.projectedAttendances)} /></div> : <Empty text="Ainda não há histórico comparável suficiente. A previsão será liberada após cinco atendimentos em cada período." />}<p className="mt-4 text-xs text-white/45">Base: {model.forecast.basis}. Isto é uma estimativa, não uma promessa de resultado.</p></div>; }
function Copilot({ model }: { model: Model }) { return <div className="rounded-3xl border border-cyan-300/20 bg-[linear-gradient(135deg,rgba(34,211,238,.12),rgba(15,23,42,.5))] p-5"><p className="text-lg font-semibold text-white">Copiloto IA</p><p className="mt-2 text-sm text-white/60">Resumo calculado com os dados reais do período selecionado.</p><ul className="mt-4 space-y-3 text-sm text-white/80">{model.insights.length ? model.insights.map((item) => <li key={item} className="rounded-xl border border-white/10 bg-black/10 p-3">{item}</li>) : <li className="rounded-xl border border-dashed border-white/10 p-3">Ainda não há dados suficientes para gerar uma análise.</li>}</ul></div>; }
function Metric({ label, value, change }: { label: string; value: string; change?: number | null }) { return <div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs uppercase tracking-[0.16em] text-white/45">{label}</p><p className="mt-2 text-xl font-semibold text-white">{value}</p>{change !== undefined ? <p className={`mt-1 text-xs ${change === null ? "text-white/45" : change >= 0 ? "text-emerald-300" : "text-rose-300"}`}>{change === null ? "Sem comparação" : `${change >= 0 ? "+" : ""}${change}% vs. período anterior`}</p> : null}</div>; }
function Amounts({ title, rows }: { title: string; rows: Array<{ label: string; amount: number }> }) { const max = Math.max(...rows.map((row) => row.amount), 1); return <div className="rounded-3xl border border-white/10 bg-black/15 p-5"><p className="text-lg font-semibold text-white">{title}</p>{rows.length ? <div className="mt-4 space-y-3">{rows.map((row) => <div key={row.label}><div className="flex justify-between gap-3 text-sm text-white/75"><span>{row.label}</span><strong className="text-white">{money(row.amount)}</strong></div><div className="mt-1 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-300" style={{ width: `${Math.max(5, row.amount / max * 100)}%` }} /></div></div>)}</div> : <Empty text="Ainda não há dados suficientes para gerar esta análise." />}</div>; }
function Counts({ title, rows }: { title: string; rows: Array<{ label: string; count: number; detail: string }> }) { return <div className="rounded-3xl border border-white/10 bg-black/15 p-5"><p className="text-lg font-semibold text-white">{title}</p>{rows.some((row) => row.count) ? <div className="mt-4 space-y-2">{rows.map((row) => <div key={row.label} className="flex justify-between gap-3 border-b border-white/8 py-2 text-sm"><span className="text-white/75">{row.label}</span><span className="text-white">{row.count} <small className="text-white/45">{row.detail}</small></span></div>)}</div> : <Empty text="Ainda não há dados suficientes para gerar esta análise." />}</div>; }
function Empty({ text }: { text: string }) { return <p className="mt-4 rounded-2xl border border-dashed border-white/10 p-4 text-sm text-white/50">{text}</p>; }
